### ISSUE TITLE
Plans/Recipies/Presets

### ISSUE THREAD

**Issue by rmcanany** [rmcanany/SolidEdgeHousekeeper#127]
Provide a way to load in settings for each step in the workflow.  I currently use a checklist to prep a job for release.  Here's part of it:

```
FIND UNUSED FILES
Select top level assembly and its folder(s).  Bottom up search, report unused files.
    Bottom up search
        Draft files same name as models.
    File list
        Sorted in alphabetical order

Update file list, check for unused files.

UPDATE PART COPIES
Select top level assembly and top level folder(s).  
    Uncheck Report files unrelated to top level assembly
    Bottom up search
        Draft files same name as models.
    File list
        Sorted in dependency order
            Uncheck Include files with no part copies

Update part copies AND Part copies out of date (Part and Sheetmetal).  
Open Save (Assembly), or possibly open the top level assy manually.
```

**Comment by rmcanany** [comment]
I'm thinking about doing this next.  I don't think it should be too hard.  My instinct is to use a Dictionary, but want to try the Class approach you suggested.

I've sketched out what I think it might look like below.  Thoughts or examples you may have would be welcome.

In `Form_Main`:
`Public Property Presets as List(Of Preset)`

Somewhere else:
```
Public Class Preset
    Public Property Name As String
    Public Property TaskList As List(Of Task)
    Public Property TaskListJSON As String
    Public Property FormSettings As Dictionary(Of String, Dictionary(Of String, String))
    Public Property FormSettingsJSON As String

    Public Sub New()
    End Sub

    Public Sub ApplyPreset()
    End Sub

    Public Sub Save()
    End Sub

    ' Etc.

End Class
```

**Comment by farfilli** [comment]
FormSettings should be a List Of(FormSetting)

FormSetting should be a Class with it's Name and Value properties

**Comment by rmcanany** [comment]
Not yet tested thoroughly, but I think it's working.  

The control is currently on the General Tab.  If you have an idea for a better location, please chime in.

One thing to note, if you want a Preset to remember Task selections, that has to be enabled on the General Tab before saving the preset.

**Comment by farfilli** [comment]
I always thought to have it on the top of the task list; I did move it with a cup-paste but stopped working so I didn't commit

![image](https://github.com/user-attachments/assets/0003b344-ff9b-4d53-a7d5-d8c0a7592a6c)

**Comment by rmcanany** [comment]
I thought it should be visible for all tab pages, so I put it just above the status bar.

![presets_toolbar](https://github.com/user-attachments/assets/e039d6dd-faf7-48e4-a11b-2b8bb90e4cdc)

Incidentally, I looked into how to move a control from one parent to another.  With the Form active in VS, go to View > Other Windows > Document Outline.  There, you can drag/drop a control as needed.  Here's a pic.

![document_outline](https://github.com/user-attachments/assets/ba9a7237-71b1-4a56-80fe-8c10792f3196)

**Comment by farfilli** [comment]
It seems a good position, I tweaked it a bit the toolbar to show buttons in the correct size.
Please note that if you save a presets with an existing name it asks to overwrite but you will have duplicate elements in the dropdown list. Also a deleted preset reappeared after the save.

**Comment by rmcanany** [comment]
OK.  I can fix that.  If you get a chance, please make a PR.  I don't want to create a bunch of merge conflicts.

**Comment by farfilli** [comment]
> OK. I can fix that. If you get a chance, please make a PR. I don't want to create a bunch of merge conflicts.

I thought I had done it... it is now 👍

**Comment by rmcanany** [comment]
Those two bugs should be fixed now.  It is supposed to work without deleting the Preferences folder, but if it acts up, please give that a try.

**Comment by farfilli** [comment]
It seems that when loading a preset nothing happens.
I did delete the preferences folder, but it still doesn't work.

**Comment by rmcanany** [comment]
I'll look at it.  If it's a Task selection not working, make sure `Remember selected tasks between sessions` is turned on.

**Comment by farfilli** [comment]
Nope, its not task selection but task list and everything else

**Comment by rmcanany** [comment]
Sure enough.  That was working before.  I'll track it down.

I'll check the comments in a bit.

**Comment by rmcanany** [comment]
I think I found the issue.  Just pushed a commit.  Please let me know if something is still not working.

**Comment by farfilli** [comment]
Tasks are still not loaded

I noticed that the windows size and position are saved within the preset, I would prefer it always stays the same and just saves on close and restore on load.

**Comment by rmcanany** [comment]
I swear that was working, but you're right.  Made another fix and uploaded just now.  Appreciate all the troubleshooting.

I'll have to look into the repositioning and resizing.

**Comment by rmcanany** [comment]
Form position and size no longer saved with the Preset.

**Comment by farfilli** [comment]
Thicked tasks are saved? It seems this part is not even saved between sessions

**Comment by rmcanany** [comment]
There's a setting `Remember selected tasks between sessions` on the Configuration Tab -- General Page.  Enable that, then save your Preset.

**Comment by farfilli** [comment]
Ticks are saved on presets as well?

Ideal workflow is to select a preset that contains only the tasks I want to run and they should be already "ticked"

**Comment by rmcanany** [comment]
Closing as complete.
